/*
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.serializer;

import com.google.inject.Inject;
import com.lowcoupling.lng.plan.services.PlanGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class PlanSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PlanGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ActivityGroup___DependsOnKeyword_5_0_ENDLINEParserRuleCall_5_2__q;
	protected AbstractElementAlias match_Activity___DependsOnKeyword_6_2_0_ENDLINEParserRuleCall_6_2_2__a;
	protected AbstractElementAlias match_Activity___ENDLINEParserRuleCall_6_2_2_DependsOnKeyword_6_2_0__a;
	protected AbstractElementAlias match_Activity___InvolvesKeyword_5_0_OPENCURLYTerminalRuleCall_5_1_CLOSEDCURLYTerminalRuleCall_5_3__q;
	protected AbstractElementAlias match_CheckPoint___DependsOnKeyword_5_1_4_0_ENDLINEParserRuleCall_5_1_4_2__q;
	protected AbstractElementAlias match_Project___AssumptionsKeyword_7_0_OPENCURLYTerminalRuleCall_7_1_CLOSEDCURLYTerminalRuleCall_7_3__q;
	protected AbstractElementAlias match_Project___ConstraintsKeyword_8_0_OPENCURLYTerminalRuleCall_8_1_CLOSEDCURLYTerminalRuleCall_8_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PlanGrammarAccess) access;
		match_ActivityGroup___DependsOnKeyword_5_0_ENDLINEParserRuleCall_5_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActivityGroupAccess().getDependsOnKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getActivityGroupAccess().getENDLINEParserRuleCall_5_2()));
		match_Activity___DependsOnKeyword_6_2_0_ENDLINEParserRuleCall_6_2_2__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getActivityAccess().getDependsOnKeyword_6_2_0()), new TokenAlias(false, false, grammarAccess.getActivityAccess().getENDLINEParserRuleCall_6_2_2()));
		match_Activity___ENDLINEParserRuleCall_6_2_2_DependsOnKeyword_6_2_0__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getActivityAccess().getENDLINEParserRuleCall_6_2_2()), new TokenAlias(false, false, grammarAccess.getActivityAccess().getDependsOnKeyword_6_2_0()));
		match_Activity___InvolvesKeyword_5_0_OPENCURLYTerminalRuleCall_5_1_CLOSEDCURLYTerminalRuleCall_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActivityAccess().getInvolvesKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getActivityAccess().getOPENCURLYTerminalRuleCall_5_1()), new TokenAlias(false, false, grammarAccess.getActivityAccess().getCLOSEDCURLYTerminalRuleCall_5_3()));
		match_CheckPoint___DependsOnKeyword_5_1_4_0_ENDLINEParserRuleCall_5_1_4_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCheckPointAccess().getDependsOnKeyword_5_1_4_0()), new TokenAlias(false, false, grammarAccess.getCheckPointAccess().getENDLINEParserRuleCall_5_1_4_2()));
		match_Project___AssumptionsKeyword_7_0_OPENCURLYTerminalRuleCall_7_1_CLOSEDCURLYTerminalRuleCall_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getProjectAccess().getAssumptionsKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getProjectAccess().getOPENCURLYTerminalRuleCall_7_1()), new TokenAlias(false, false, grammarAccess.getProjectAccess().getCLOSEDCURLYTerminalRuleCall_7_3()));
		match_Project___ConstraintsKeyword_8_0_OPENCURLYTerminalRuleCall_8_1_CLOSEDCURLYTerminalRuleCall_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getProjectAccess().getConstraintsKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getProjectAccess().getOPENCURLYTerminalRuleCall_8_1()), new TokenAlias(false, false, grammarAccess.getProjectAccess().getCLOSEDCURLYTerminalRuleCall_8_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getCLOSEDCURLYRule())
			return getCLOSEDCURLYToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getENDLINERule())
			return getENDLINEToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getOPENCURLYRule())
			return getOPENCURLYToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal CLOSEDCURLY :
	 * 	'}'
	 * ;
	 */
	protected String getCLOSEDCURLYToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "}";
	}
	
	/**
	 * ENDLINE:
	 * 	";"
	 * ;
	 */
	protected String getENDLINEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ";";
	}
	
	/**
	 * terminal OPENCURLY :
	 * 	'{'
	 * ;
	 */
	protected String getOPENCURLYToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "{";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_ActivityGroup___DependsOnKeyword_5_0_ENDLINEParserRuleCall_5_2__q.equals(syntax))
				emit_ActivityGroup___DependsOnKeyword_5_0_ENDLINEParserRuleCall_5_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Activity___DependsOnKeyword_6_2_0_ENDLINEParserRuleCall_6_2_2__a.equals(syntax))
				emit_Activity___DependsOnKeyword_6_2_0_ENDLINEParserRuleCall_6_2_2__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Activity___ENDLINEParserRuleCall_6_2_2_DependsOnKeyword_6_2_0__a.equals(syntax))
				emit_Activity___ENDLINEParserRuleCall_6_2_2_DependsOnKeyword_6_2_0__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Activity___InvolvesKeyword_5_0_OPENCURLYTerminalRuleCall_5_1_CLOSEDCURLYTerminalRuleCall_5_3__q.equals(syntax))
				emit_Activity___InvolvesKeyword_5_0_OPENCURLYTerminalRuleCall_5_1_CLOSEDCURLYTerminalRuleCall_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_CheckPoint___DependsOnKeyword_5_1_4_0_ENDLINEParserRuleCall_5_1_4_2__q.equals(syntax))
				emit_CheckPoint___DependsOnKeyword_5_1_4_0_ENDLINEParserRuleCall_5_1_4_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Project___AssumptionsKeyword_7_0_OPENCURLYTerminalRuleCall_7_1_CLOSEDCURLYTerminalRuleCall_7_3__q.equals(syntax))
				emit_Project___AssumptionsKeyword_7_0_OPENCURLYTerminalRuleCall_7_1_CLOSEDCURLYTerminalRuleCall_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Project___ConstraintsKeyword_8_0_OPENCURLYTerminalRuleCall_8_1_CLOSEDCURLYTerminalRuleCall_8_3__q.equals(syntax))
				emit_Project___ConstraintsKeyword_8_0_OPENCURLYTerminalRuleCall_8_1_CLOSEDCURLYTerminalRuleCall_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('dependsOn' ENDLINE)?
	 *
	 * This ambiguous syntax occurs at:
	 *     longName=STRING ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 *     longName=STRING ENDLINE (ambiguity) activities+=ActivityElement
	 *     name=ID OPENCURLY (ambiguity) CLOSEDCURLY (rule end)
	 *     name=ID OPENCURLY (ambiguity) activities+=ActivityElement
	 */
	protected void emit_ActivityGroup___DependsOnKeyword_5_0_ENDLINEParserRuleCall_5_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('dependsOn' ENDLINE)*
	 *
	 * This ambiguous syntax occurs at:
	 *     completeness=INT '%' ENDLINE (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     completeness=INT '%' ENDLINE (ambiguity) 'duration' duration=INT
	 *     completeness=INT '%' ENDLINE (ambiguity) 'ends' end=STRING
	 *     completeness=INT '%' ENDLINE (ambiguity) 'starts' start=STRING
	 *     completeness=INT '%' ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 *     dependencies+=[ActivityElement|QualifiedName] ENDLINE (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     dependencies+=[ActivityElement|QualifiedName] ENDLINE (ambiguity) 'duration' duration=INT
	 *     dependencies+=[ActivityElement|QualifiedName] ENDLINE (ambiguity) 'ends' end=STRING
	 *     dependencies+=[ActivityElement|QualifiedName] ENDLINE (ambiguity) 'starts' start=STRING
	 *     dependencies+=[ActivityElement|QualifiedName] ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY (ambiguity) 'duration' duration=INT
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY (ambiguity) 'ends' end=STRING
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY (ambiguity) 'starts' start=STRING
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY (ambiguity) CLOSEDCURLY (rule end)
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'duration' duration=INT
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'ends' end=STRING
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'starts' start=STRING
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'duration' duration=INT
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'ends' end=STRING
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) 'starts' start=STRING
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     offset=INT ENDLINE (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     offset=INT ENDLINE (ambiguity) 'duration' duration=INT
	 *     offset=INT ENDLINE (ambiguity) 'ends' end=STRING
	 *     offset=INT ENDLINE (ambiguity) 'starts' start=STRING
	 *     offset=INT ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 *     start=STRING ENDLINE (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     start=STRING ENDLINE (ambiguity) 'duration' duration=INT
	 *     start=STRING ENDLINE (ambiguity) 'ends' end=STRING
	 *     start=STRING ENDLINE (ambiguity) 'starts' start=STRING
	 *     start=STRING ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 */
	protected void emit_Activity___DependsOnKeyword_6_2_0_ENDLINEParserRuleCall_6_2_2__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (ENDLINE 'dependsOn')*
	 *
	 * This ambiguous syntax occurs at:
	 *     completeness=INT '%' ENDLINE 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     dependencies+=[ActivityElement|QualifiedName] (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     involvedResources+=ResourceInvolvement CLOSEDCURLY 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     longName=STRING ENDLINE ('involves' OPENCURLY CLOSEDCURLY)? 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     name=ID OPENCURLY ('involves' OPENCURLY CLOSEDCURLY)? 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     offset=INT ENDLINE 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 *     start=STRING ENDLINE 'dependsOn' (ambiguity) dependencies+=[ActivityElement|QualifiedName]
	 */
	protected void emit_Activity___ENDLINEParserRuleCall_6_2_2_DependsOnKeyword_6_2_0__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('involves' OPENCURLY CLOSEDCURLY)?
	 *
	 * This ambiguous syntax occurs at:
	 *     longName=STRING ENDLINE (ambiguity) 'dependsOn' (ENDLINE 'dependsOn')* dependencies+=[ActivityElement|QualifiedName]
	 *     longName=STRING ENDLINE (ambiguity) ('dependsOn' ENDLINE)* 'after' after=[ActivityElement|QualifiedName]
	 *     longName=STRING ENDLINE (ambiguity) ('dependsOn' ENDLINE)* 'duration' duration=INT
	 *     longName=STRING ENDLINE (ambiguity) ('dependsOn' ENDLINE)* 'ends' end=STRING
	 *     longName=STRING ENDLINE (ambiguity) ('dependsOn' ENDLINE)* 'starts' start=STRING
	 *     longName=STRING ENDLINE (ambiguity) ('dependsOn' ENDLINE)* CLOSEDCURLY (rule end)
	 *     name=ID OPENCURLY (ambiguity) 'dependsOn' (ENDLINE 'dependsOn')* dependencies+=[ActivityElement|QualifiedName]
	 *     name=ID OPENCURLY (ambiguity) ('dependsOn' ENDLINE)* 'after' after=[ActivityElement|QualifiedName]
	 *     name=ID OPENCURLY (ambiguity) ('dependsOn' ENDLINE)* 'duration' duration=INT
	 *     name=ID OPENCURLY (ambiguity) ('dependsOn' ENDLINE)* 'ends' end=STRING
	 *     name=ID OPENCURLY (ambiguity) ('dependsOn' ENDLINE)* 'starts' start=STRING
	 *     name=ID OPENCURLY (ambiguity) ('dependsOn' ENDLINE)* CLOSEDCURLY (rule end)
	 */
	protected void emit_Activity___InvolvesKeyword_5_0_OPENCURLYTerminalRuleCall_5_1_CLOSEDCURLYTerminalRuleCall_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('dependsOn' ENDLINE)?
	 *
	 * This ambiguous syntax occurs at:
	 *     completeness=INT '%' ENDLINE (ambiguity) 'after' after=[ActivityElement|QualifiedName]
	 *     completeness=INT '%' ENDLINE (ambiguity) 'completeness' completeness=INT
	 *     completeness=INT '%' ENDLINE (ambiguity) 'date' end=STRING
	 *     completeness=INT '%' ENDLINE (ambiguity) CLOSEDCURLY (rule end)
	 */
	protected void emit_CheckPoint___DependsOnKeyword_5_1_4_0_ENDLINEParserRuleCall_5_1_4_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('assumptions' OPENCURLY CLOSEDCURLY)?
	 *
	 * This ambiguous syntax occurs at:
	 *     longName=STRING ENDLINE (ambiguity) 'constraints' OPENCURLY constraints+=Constraint
	 *     longName=STRING ENDLINE (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? CLOSEDCURLY (rule end)
	 *     longName=STRING ENDLINE (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? activities+=ActivityElement
	 *     name=ID OPENCURLY (ambiguity) 'constraints' OPENCURLY constraints+=Constraint
	 *     name=ID OPENCURLY (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? CLOSEDCURLY (rule end)
	 *     name=ID OPENCURLY (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? activities+=ActivityElement
	 *     plans+=PlanImport ENDLINE (ambiguity) 'constraints' OPENCURLY constraints+=Constraint
	 *     plans+=PlanImport ENDLINE (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? CLOSEDCURLY (rule end)
	 *     plans+=PlanImport ENDLINE (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? activities+=ActivityElement
	 *     resources=Resources (ambiguity) 'constraints' OPENCURLY constraints+=Constraint
	 *     resources=Resources (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? CLOSEDCURLY (rule end)
	 *     resources=Resources (ambiguity) ('constraints' OPENCURLY CLOSEDCURLY)? activities+=ActivityElement
	 */
	protected void emit_Project___AssumptionsKeyword_7_0_OPENCURLYTerminalRuleCall_7_1_CLOSEDCURLYTerminalRuleCall_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('constraints' OPENCURLY CLOSEDCURLY)?
	 *
	 * This ambiguous syntax occurs at:
	 *     assumptions+=Assumption CLOSEDCURLY (ambiguity) CLOSEDCURLY (rule end)
	 *     assumptions+=Assumption CLOSEDCURLY (ambiguity) activities+=ActivityElement
	 *     longName=STRING ENDLINE ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     longName=STRING ENDLINE ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) activities+=ActivityElement
	 *     name=ID OPENCURLY ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     name=ID OPENCURLY ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) activities+=ActivityElement
	 *     plans+=PlanImport ENDLINE ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     plans+=PlanImport ENDLINE ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) activities+=ActivityElement
	 *     resources=Resources ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) CLOSEDCURLY (rule end)
	 *     resources=Resources ('assumptions' OPENCURLY CLOSEDCURLY)? (ambiguity) activities+=ActivityElement
	 */
	protected void emit_Project___ConstraintsKeyword_8_0_OPENCURLYTerminalRuleCall_8_1_CLOSEDCURLYTerminalRuleCall_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
