/*
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.lowcoupling.lng.plan.services.PlanGrammarAccess;

public class PlanParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PlanGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.lowcoupling.lng.plan.parser.antlr.internal.InternalPlanParser createParser(XtextTokenStream stream) {
		return new com.lowcoupling.lng.plan.parser.antlr.internal.InternalPlanParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public PlanGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlanGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
