/**
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.validation;

import com.lowcoupling.lng.plan.validation.AbstractPlanValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PlanValidator extends AbstractPlanValidator {
}
