/*
* generated by Xtext
*/
package com.lowcoupling.lng.plan.ui.outline;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import org.eclipse.core.runtime.Platform;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Display;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.osgi.framework.Bundle;

import com.lowcoupling.lng.plan.plan.Activity;
import com.lowcoupling.lng.plan.plan.ActivityGroup;
import com.lowcoupling.lng.plan.plan.CheckPoint;
import com.lowcoupling.lng.plan.plan.Program;
import com.lowcoupling.lng.plan.plan.Project;

/**
 * customization of the default outline structure
 * 
 */
public class PlanOutlineTreeProvider extends DefaultOutlineTreeProvider {
	@Override
	protected Image _image(Object modelElement) {
		// TODO Auto-generated method stub
		//return super._image(modelElement);
		
		Bundle bundle = Platform.getBundle("com.lowcoupling.lng.plan.ui");
		if (bundle==null){
			return null;
		}
		if (modelElement instanceof Project){
			URL planIconUrl = bundle.getEntry("/images/Plan_Icon.png");
			InputStream in = null;
			try {
				in = planIconUrl.openConnection().getInputStream();
				Image img = new Image(Display.getCurrent(), in);
				in.close();
				return img; 	
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (modelElement instanceof Program){
			URL programIconUrl = bundle.getEntry("/images/Program_Icon.png");
			InputStream in = null;
			try {
				in = programIconUrl.openConnection().getInputStream();
				Image img = new Image(Display.getCurrent(), in);
				in.close();
				return img;
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (modelElement instanceof Activity){
			URL activityIconUrl = bundle.getEntry("/images/Activity_Icon.png");
			InputStream in = null;
			try {
				in = activityIconUrl.openConnection().getInputStream();
				Image img = new Image(Display.getCurrent(), in);
				in.close();
				return img;
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (modelElement instanceof CheckPoint){
			URL planIconUrl = bundle.getEntry("/images/CheckPoint_Icon.png");
			InputStream in = null;
			try {
				in = planIconUrl.openConnection().getInputStream();
				Image img = new Image(Display.getCurrent(), in);
				in.close();
				return img; 	
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		if (modelElement instanceof ActivityGroup){
			URL planIconUrl = bundle.getEntry("/images/GroupIcon.png");
			InputStream in = null;
			try {
				in = planIconUrl.openConnection().getInputStream();
				Image img = new Image(Display.getCurrent(), in);
				in.close();
				return img; 	
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		return super._image(modelElement);
	}

}
