/*
* generated by Xtext
*/
package com.lowcoupling.lng.plan.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class PlanDescriptionLabelProvider extends DefaultDescriptionLabelProvider {


	//Labels and icons can be computed like this:
	
	public String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
/*	 
    String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 
*/

}
