/*
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlanUiModule extends com.lowcoupling.lng.plan.ui.AbstractPlanUiModule {
	static public AbstractUIPlugin _plugin;
	public PlanUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		_plugin = plugin;
		
	}
	 public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
	        return PlanHoverProvider.class;
	 }
	 
	 public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
	        return PlanDocumentationProvider.class;
	    }
	 
//	 public Class<? extends XtextEditor> bindEditor() {
//		 	return PlanEditor.class;
//	 }
}
