/*
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PlanGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0_0 = (RuleCall)cDescriptionAssignment_0_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Keyword cProgramKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cNameAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_1_0 = (RuleCall)cNameAssignment_0_1_1.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_0_1_2 = (RuleCall)cGroup_0_1.eContents().get(2);
		private final Group cGroup_0_1_3 = (Group)cGroup_0_1.eContents().get(3);
		private final Keyword cNameKeyword_0_1_3_0 = (Keyword)cGroup_0_1_3.eContents().get(0);
		private final Assignment cLongNameAssignment_0_1_3_1 = (Assignment)cGroup_0_1_3.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_0_1_3_1_0 = (RuleCall)cLongNameAssignment_0_1_3_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_0_1_3_2 = (RuleCall)cGroup_0_1_3.eContents().get(2);
		private final Group cGroup_0_1_4 = (Group)cGroup_0_1.eContents().get(4);
		private final Assignment cPlansAssignment_0_1_4_0 = (Assignment)cGroup_0_1_4.eContents().get(0);
		private final RuleCall cPlansPlanImportParserRuleCall_0_1_4_0_0 = (RuleCall)cPlansAssignment_0_1_4_0.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_0_1_4_1 = (RuleCall)cGroup_0_1_4.eContents().get(1);
		private final Group cGroup_0_1_5 = (Group)cGroup_0_1.eContents().get(5);
		private final Keyword cProjectKeyword_0_1_5_0 = (Keyword)cGroup_0_1_5.eContents().get(0);
		private final Assignment cReferencedProjectsAssignment_0_1_5_1 = (Assignment)cGroup_0_1_5.eContents().get(1);
		private final CrossReference cReferencedProjectsProjectCrossReference_0_1_5_1_0 = (CrossReference)cReferencedProjectsAssignment_0_1_5_1.eContents().get(0);
		private final RuleCall cReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1 = (RuleCall)cReferencedProjectsProjectCrossReference_0_1_5_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_0_1_5_2 = (RuleCall)cGroup_0_1_5.eContents().get(2);
		private final Assignment cProjectsAssignment_0_1_6 = (Assignment)cGroup_0_1.eContents().get(6);
		private final RuleCall cProjectsProjectParserRuleCall_0_1_6_0 = (RuleCall)cProjectsAssignment_0_1_6.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_0_1_7 = (RuleCall)cGroup_0_1.eContents().get(7);
		private final Assignment cProjectsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cProjectsProjectParserRuleCall_1_0 = (RuleCall)cProjectsAssignment_1.eContents().get(0);
		
		//Program:
		//	description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//	("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project;
		@Override public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project
		public Alternatives getAlternatives() { return cAlternatives; }

		//description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY)
		public Group getGroup_0() { return cGroup_0; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0_0() { return cDescriptionAssignment_0_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0_0; }

		//"Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)* ("project"
		//referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"Program"
		public Keyword getProgramKeyword_0_1_0() { return cProgramKeyword_0_1_0; }

		//name=ID
		public Assignment getNameAssignment_0_1_1() { return cNameAssignment_0_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_1_0() { return cNameIDTerminalRuleCall_0_1_1_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_0_1_2() { return cOPENCURLYTerminalRuleCall_0_1_2; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_0_1_3() { return cGroup_0_1_3; }

		//"name"
		public Keyword getNameKeyword_0_1_3_0() { return cNameKeyword_0_1_3_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_0_1_3_1() { return cLongNameAssignment_0_1_3_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_0_1_3_1_0() { return cLongNameSTRINGTerminalRuleCall_0_1_3_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_3_2() { return cENDLINEParserRuleCall_0_1_3_2; }

		//(plans+=PlanImport ENDLINE)*
		public Group getGroup_0_1_4() { return cGroup_0_1_4; }

		//plans+=PlanImport
		public Assignment getPlansAssignment_0_1_4_0() { return cPlansAssignment_0_1_4_0; }

		//PlanImport
		public RuleCall getPlansPlanImportParserRuleCall_0_1_4_0_0() { return cPlansPlanImportParserRuleCall_0_1_4_0_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_4_1() { return cENDLINEParserRuleCall_0_1_4_1; }

		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)*
		public Group getGroup_0_1_5() { return cGroup_0_1_5; }

		//"project"
		public Keyword getProjectKeyword_0_1_5_0() { return cProjectKeyword_0_1_5_0; }

		//referencedProjects+=[Project|QualifiedName]
		public Assignment getReferencedProjectsAssignment_0_1_5_1() { return cReferencedProjectsAssignment_0_1_5_1; }

		//[Project|QualifiedName]
		public CrossReference getReferencedProjectsProjectCrossReference_0_1_5_1_0() { return cReferencedProjectsProjectCrossReference_0_1_5_1_0; }

		//QualifiedName
		public RuleCall getReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1() { return cReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_5_2() { return cENDLINEParserRuleCall_0_1_5_2; }

		//projects+=Project*
		public Assignment getProjectsAssignment_0_1_6() { return cProjectsAssignment_0_1_6; }

		//Project
		public RuleCall getProjectsProjectParserRuleCall_0_1_6_0() { return cProjectsProjectParserRuleCall_0_1_6_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_0_1_7() { return cCLOSEDCURLYTerminalRuleCall_0_1_7; }

		//projects+=Project
		public Assignment getProjectsAssignment_1() { return cProjectsAssignment_1; }

		//Project
		public RuleCall getProjectsProjectParserRuleCall_1_0() { return cProjectsProjectParserRuleCall_1_0; }
	}

	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cProjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Assignment cResourcesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cResourcesResourcesParserRuleCall_5_0 = (RuleCall)cResourcesAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cPlansAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cPlansPlanImportParserRuleCall_6_0_0 = (RuleCall)cPlansAssignment_6_0.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_1 = (RuleCall)cGroup_6.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAssumptionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_7_1 = (RuleCall)cGroup_7.eContents().get(1);
		private final Assignment cAssumptionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAssumptionsAssumptionParserRuleCall_7_2_0 = (RuleCall)cAssumptionsAssignment_7_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_7_3 = (RuleCall)cGroup_7.eContents().get(3);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cConstraintsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_8_1 = (RuleCall)cGroup_8.eContents().get(1);
		private final Assignment cConstraintsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_8_2_0 = (RuleCall)cConstraintsAssignment_8_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_8_3 = (RuleCall)cGroup_8.eContents().get(3);
		private final Assignment cActivitiesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cActivitiesActivityElementParserRuleCall_9_0 = (RuleCall)cActivitiesAssignment_9.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		
		//Project:
		//	description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? resources=Resources?
		//	(plans+=PlanImport ENDLINE)* ("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY
		//	constraints+=Constraint* CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY;
		@Override public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? resources=Resources?
		//(plans+=PlanImport ENDLINE)* ("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY
		//constraints+=Constraint* CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Project"
		public Keyword getProjectKeyword_1() { return cProjectKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//resources=Resources?
		public Assignment getResourcesAssignment_5() { return cResourcesAssignment_5; }

		//Resources
		public RuleCall getResourcesResourcesParserRuleCall_5_0() { return cResourcesResourcesParserRuleCall_5_0; }

		//(plans+=PlanImport ENDLINE)*
		public Group getGroup_6() { return cGroup_6; }

		//plans+=PlanImport
		public Assignment getPlansAssignment_6_0() { return cPlansAssignment_6_0; }

		//PlanImport
		public RuleCall getPlansPlanImportParserRuleCall_6_0_0() { return cPlansPlanImportParserRuleCall_6_0_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_1() { return cENDLINEParserRuleCall_6_1; }

		//("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)?
		public Group getGroup_7() { return cGroup_7; }

		//"assumptions"
		public Keyword getAssumptionsKeyword_7_0() { return cAssumptionsKeyword_7_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_7_1() { return cOPENCURLYTerminalRuleCall_7_1; }

		//assumptions+=Assumption*
		public Assignment getAssumptionsAssignment_7_2() { return cAssumptionsAssignment_7_2; }

		//Assumption
		public RuleCall getAssumptionsAssumptionParserRuleCall_7_2_0() { return cAssumptionsAssumptionParserRuleCall_7_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_7_3() { return cCLOSEDCURLYTerminalRuleCall_7_3; }

		//("constraints" OPENCURLY constraints+=Constraint* CLOSEDCURLY)?
		public Group getGroup_8() { return cGroup_8; }

		//"constraints"
		public Keyword getConstraintsKeyword_8_0() { return cConstraintsKeyword_8_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_8_1() { return cOPENCURLYTerminalRuleCall_8_1; }

		//constraints+=Constraint*
		public Assignment getConstraintsAssignment_8_2() { return cConstraintsAssignment_8_2; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_8_2_0() { return cConstraintsConstraintParserRuleCall_8_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_8_3() { return cCLOSEDCURLYTerminalRuleCall_8_3; }

		//activities+=ActivityElement*
		public Assignment getActivitiesAssignment_9() { return cActivitiesAssignment_9; }

		//ActivityElement
		public RuleCall getActivitiesActivityElementParserRuleCall_9_0() { return cActivitiesActivityElementParserRuleCall_9_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_10() { return cCLOSEDCURLYTerminalRuleCall_10; }
	}

	public class AssumptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assumption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Assumption:
		//	"-" value=STRING ENDLINE;
		@Override public ParserRule getRule() { return rule; }

		//"-" value=STRING ENDLINE
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_2() { return cENDLINEParserRuleCall_2; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Constraint:
		//	"-" value=STRING ENDLINE;
		@Override public ParserRule getRule() { return rule; }

		//"-" value=STRING ENDLINE
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_2() { return cENDLINEParserRuleCall_2; }
	}

	public class ActivityGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActivityGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cGroupKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDependsOnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDependenciesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_5_1_0 = (CrossReference)cDependenciesAssignment_5_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_5_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_5_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_5_2 = (RuleCall)cGroup_5.eContents().get(2);
		private final Assignment cActivitiesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActivitiesActivityElementParserRuleCall_6_0 = (RuleCall)cActivitiesAssignment_6.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		
		//ActivityGroup:
		//	description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("dependsOn"
		//	dependencies+=[ActivityElement|QualifiedName]* ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
		//	CLOSEDCURLY;
		@Override public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("dependsOn"
		//dependencies+=[ActivityElement|QualifiedName]* ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
		//CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Group"
		public Keyword getGroupKeyword_1() { return cGroupKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_5() { return cGroup_5; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_5_0() { return cDependsOnKeyword_5_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_5_1() { return cDependenciesAssignment_5_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_5_1_0() { return cDependenciesActivityElementCrossReference_5_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_5_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_5_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_2() { return cENDLINEParserRuleCall_5_2; }

		//activities+=ActivityElement*
		public Assignment getActivitiesAssignment_6() { return cActivitiesAssignment_6; }

		//ActivityElement
		public RuleCall getActivitiesActivityElementParserRuleCall_6_0() { return cActivitiesActivityElementParserRuleCall_6_0; }

		////groups += ActivityGroup*
		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_7() { return cCLOSEDCURLYTerminalRuleCall_7; }
	}

	public class WBSImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WBSImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWbsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//WBSImport:
		//	"wbs" importURI= // feature must be named importURI
		//	STRING;
		@Override public ParserRule getRule() { return rule; }

		//"wbs" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"wbs"
		public Keyword getWbsKeyword_0() { return cWbsKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class ResourcesImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourcesImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//ResourcesImport:
		//	"resources" importURI= // feature must be named importURI
		//	STRING;
		@Override public ParserRule getRule() { return rule; }

		//"resources" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"resources"
		public Keyword getResourcesKeyword_0() { return cResourcesKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class PlanImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PlanImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//PlanImport:
		//	"plan" importURI= // feature must be named importURI
		//	STRING;
		@Override public ParserRule getRule() { return rule; }

		//"plan" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"plan"
		public Keyword getPlanKeyword_0() { return cPlanKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		@Override public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class QualifiedNameWithWildCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedNameWithWildCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildCard:
		//	QualifiedName ".*"?;
		@Override public ParserRule getRule() { return rule; }

		//QualifiedName ".*"?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//".*"?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}

	public class ActivityElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActivityElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCheckPointParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cActivityGroupParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ActivityElement:
		//	Activity | CheckPoint | ActivityGroup;
		@Override public ParserRule getRule() { return rule; }

		//Activity | CheckPoint | ActivityGroup
		public Alternatives getAlternatives() { return cAlternatives; }

		//Activity
		public RuleCall getActivityParserRuleCall_0() { return cActivityParserRuleCall_0; }

		//CheckPoint
		public RuleCall getCheckPointParserRuleCall_1() { return cCheckPointParserRuleCall_1; }

		//ActivityGroup
		public RuleCall getActivityGroupParserRuleCall_2() { return cActivityGroupParserRuleCall_2; }
	}

	public class ENDLINEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ENDLINE");
		private final Keyword cSemicolonKeyword = (Keyword)rule.eContents().get(1);
		
		//ENDLINE:
		//	";";
		@Override public ParserRule getRule() { return rule; }

		//";"
		public Keyword getSemicolonKeyword() { return cSemicolonKeyword; }
	}

	public class ResourcesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Resources");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cResourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cResourceResourceParserRuleCall_2_0 = (RuleCall)cResourceAssignment_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Resources:
		//	"Resources" OPENCURLY resource+=Resource* CLOSEDCURLY;
		@Override public ParserRule getRule() { return rule; }

		//"Resources" OPENCURLY resource+=Resource* CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//"Resources"
		public Keyword getResourcesKeyword_0() { return cResourcesKeyword_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_1() { return cOPENCURLYTerminalRuleCall_1; }

		//resource+=Resource*
		public Assignment getResourceAssignment_2() { return cResourceAssignment_2; }

		//Resource
		public RuleCall getResourceResourceParserRuleCall_2_0() { return cResourceResourceParserRuleCall_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_3() { return cCLOSEDCURLYTerminalRuleCall_3; }
	}

	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Resource:
		//	"Resource" name=STRING ENDLINE;
		@Override public ParserRule getRule() { return rule; }

		//"Resource" name=STRING ENDLINE
		public Group getGroup() { return cGroup; }

		//"Resource"
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_2() { return cENDLINEParserRuleCall_2; }
	}

	public class CheckPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CheckPoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cCheckPointKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_5 = (UnorderedGroup)cGroup.eContents().get(5);
		private final Alternatives cAlternatives_5_0 = (Alternatives)cUnorderedGroup_5.eContents().get(0);
		private final Group cGroup_5_0_0 = (Group)cAlternatives_5_0.eContents().get(0);
		private final Keyword cDateKeyword_5_0_0_0 = (Keyword)cGroup_5_0_0.eContents().get(0);
		private final Assignment cEndAssignment_5_0_0_1 = (Assignment)cGroup_5_0_0.eContents().get(1);
		private final RuleCall cEndSTRINGTerminalRuleCall_5_0_0_1_0 = (RuleCall)cEndAssignment_5_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_5_0_0_2 = (RuleCall)cGroup_5_0_0.eContents().get(2);
		private final Group cGroup_5_0_1 = (Group)cAlternatives_5_0.eContents().get(1);
		private final Keyword cAfterKeyword_5_0_1_0 = (Keyword)cGroup_5_0_1.eContents().get(0);
		private final Assignment cAfterAssignment_5_0_1_1 = (Assignment)cGroup_5_0_1.eContents().get(1);
		private final CrossReference cAfterActivityElementCrossReference_5_0_1_1_0 = (CrossReference)cAfterAssignment_5_0_1_1.eContents().get(0);
		private final RuleCall cAfterActivityElementQualifiedNameParserRuleCall_5_0_1_1_0_1 = (RuleCall)cAfterActivityElementCrossReference_5_0_1_1_0.eContents().get(1);
		private final Keyword cOffsetKeyword_5_0_1_2 = (Keyword)cGroup_5_0_1.eContents().get(2);
		private final Assignment cOffsetAssignment_5_0_1_3 = (Assignment)cGroup_5_0_1.eContents().get(3);
		private final RuleCall cOffsetINTTerminalRuleCall_5_0_1_3_0 = (RuleCall)cOffsetAssignment_5_0_1_3.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_5_0_1_4 = (RuleCall)cGroup_5_0_1.eContents().get(4);
		private final Group cGroup_5_1 = (Group)cUnorderedGroup_5.eContents().get(1);
		private final Keyword cCompletenessKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cCompletenessAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cCompletenessINTTerminalRuleCall_5_1_1_0 = (RuleCall)cCompletenessAssignment_5_1_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_5_1_2 = (Keyword)cGroup_5_1.eContents().get(2);
		private final RuleCall cENDLINEParserRuleCall_5_1_3 = (RuleCall)cGroup_5_1.eContents().get(3);
		private final Group cGroup_5_1_4 = (Group)cGroup_5_1.eContents().get(4);
		private final Keyword cDependsOnKeyword_5_1_4_0 = (Keyword)cGroup_5_1_4.eContents().get(0);
		private final Assignment cDependenciesAssignment_5_1_4_1 = (Assignment)cGroup_5_1_4.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_5_1_4_1_0 = (CrossReference)cDependenciesAssignment_5_1_4_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_5_1_4_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_5_1_4_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_5_1_4_2 = (RuleCall)cGroup_5_1_4.eContents().get(2);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		
		//CheckPoint:
		//	description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (("date" end=STRING ENDLINE |
		//	"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%"
		//	ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
		@Override public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (("date" end=STRING ENDLINE |
		//"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%"
		//ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"CheckPoint"
		public Keyword getCheckPointKeyword_1() { return cCheckPointKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//("date" end=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness"
		//completeness=INT "%" ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public UnorderedGroup getUnorderedGroup_5() { return cUnorderedGroup_5; }

		//"date" end=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Alternatives getAlternatives_5_0() { return cAlternatives_5_0; }

		//"date" end=STRING ENDLINE
		public Group getGroup_5_0_0() { return cGroup_5_0_0; }

		//"date"
		public Keyword getDateKeyword_5_0_0_0() { return cDateKeyword_5_0_0_0; }

		//end=STRING
		public Assignment getEndAssignment_5_0_0_1() { return cEndAssignment_5_0_0_1; }

		//STRING
		public RuleCall getEndSTRINGTerminalRuleCall_5_0_0_1_0() { return cEndSTRINGTerminalRuleCall_5_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_0_0_2() { return cENDLINEParserRuleCall_5_0_0_2; }

		//"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Group getGroup_5_0_1() { return cGroup_5_0_1; }

		//"after"
		public Keyword getAfterKeyword_5_0_1_0() { return cAfterKeyword_5_0_1_0; }

		//after=[ActivityElement|QualifiedName]
		public Assignment getAfterAssignment_5_0_1_1() { return cAfterAssignment_5_0_1_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getAfterActivityElementCrossReference_5_0_1_1_0() { return cAfterActivityElementCrossReference_5_0_1_1_0; }

		//QualifiedName
		public RuleCall getAfterActivityElementQualifiedNameParserRuleCall_5_0_1_1_0_1() { return cAfterActivityElementQualifiedNameParserRuleCall_5_0_1_1_0_1; }

		//"offset"
		public Keyword getOffsetKeyword_5_0_1_2() { return cOffsetKeyword_5_0_1_2; }

		//offset=INT
		public Assignment getOffsetAssignment_5_0_1_3() { return cOffsetAssignment_5_0_1_3; }

		//INT
		public RuleCall getOffsetINTTerminalRuleCall_5_0_1_3_0() { return cOffsetINTTerminalRuleCall_5_0_1_3_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_0_1_4() { return cENDLINEParserRuleCall_5_0_1_4; }

		//"completeness" completeness=INT "%" ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_5_1() { return cGroup_5_1; }

		//"completeness"
		public Keyword getCompletenessKeyword_5_1_0() { return cCompletenessKeyword_5_1_0; }

		//completeness=INT
		public Assignment getCompletenessAssignment_5_1_1() { return cCompletenessAssignment_5_1_1; }

		//INT
		public RuleCall getCompletenessINTTerminalRuleCall_5_1_1_0() { return cCompletenessINTTerminalRuleCall_5_1_1_0; }

		//"%"
		public Keyword getPercentSignKeyword_5_1_2() { return cPercentSignKeyword_5_1_2; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_1_3() { return cENDLINEParserRuleCall_5_1_3; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_5_1_4() { return cGroup_5_1_4; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_5_1_4_0() { return cDependsOnKeyword_5_1_4_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_5_1_4_1() { return cDependenciesAssignment_5_1_4_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_5_1_4_1_0() { return cDependenciesActivityElementCrossReference_5_1_4_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_5_1_4_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_5_1_4_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_1_4_2() { return cENDLINEParserRuleCall_5_1_4_2; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_6() { return cCLOSEDCURLYTerminalRuleCall_6; }
	}

	public class ResourceInvolvementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceInvolvement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cResourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cResourceResourceCrossReference_0_0 = (CrossReference)cResourceAssignment_0.eContents().get(0);
		private final RuleCall cResourceResourceIDTerminalRuleCall_0_0_1 = (RuleCall)cResourceResourceCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAtKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cOccupationAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOccupationINTTerminalRuleCall_1_1_0 = (RuleCall)cOccupationAssignment_1_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cResponsibilityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cResponsibilityResponsibilityEnumRuleCall_2_1_0 = (RuleCall)cResponsibilityAssignment_2_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//ResourceInvolvement:
		//	resource=[Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE;
		@Override public ParserRule getRule() { return rule; }

		//resource=[Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE
		public Group getGroup() { return cGroup; }

		//resource=[Resource]
		public Assignment getResourceAssignment_0() { return cResourceAssignment_0; }

		//[Resource]
		public CrossReference getResourceResourceCrossReference_0_0() { return cResourceResourceCrossReference_0_0; }

		//ID
		public RuleCall getResourceResourceIDTerminalRuleCall_0_0_1() { return cResourceResourceIDTerminalRuleCall_0_0_1; }

		//("at" occupation=INT "%")?
		public Group getGroup_1() { return cGroup_1; }

		//"at"
		public Keyword getAtKeyword_1_0() { return cAtKeyword_1_0; }

		//occupation=INT
		public Assignment getOccupationAssignment_1_1() { return cOccupationAssignment_1_1; }

		//INT
		public RuleCall getOccupationINTTerminalRuleCall_1_1_0() { return cOccupationINTTerminalRuleCall_1_1_0; }

		//"%"
		public Keyword getPercentSignKeyword_1_2() { return cPercentSignKeyword_1_2; }

		//("as" responsibility=Responsibility)?
		public Group getGroup_2() { return cGroup_2; }

		//"as"
		public Keyword getAsKeyword_2_0() { return cAsKeyword_2_0; }

		//responsibility=Responsibility
		public Assignment getResponsibilityAssignment_2_1() { return cResponsibilityAssignment_2_1; }

		//Responsibility
		public RuleCall getResponsibilityResponsibilityEnumRuleCall_2_1_0() { return cResponsibilityResponsibilityEnumRuleCall_2_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_3() { return cENDLINEParserRuleCall_3; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInvolvesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_5_1 = (RuleCall)cGroup_5.eContents().get(1);
		private final Assignment cInvolvedResourcesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0 = (RuleCall)cInvolvedResourcesAssignment_5_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_5_3 = (RuleCall)cGroup_5.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_6 = (UnorderedGroup)cGroup.eContents().get(6);
		private final Alternatives cAlternatives_6_0 = (Alternatives)cUnorderedGroup_6.eContents().get(0);
		private final Group cGroup_6_0_0 = (Group)cAlternatives_6_0.eContents().get(0);
		private final Keyword cStartsKeyword_6_0_0_0 = (Keyword)cGroup_6_0_0.eContents().get(0);
		private final Assignment cStartAssignment_6_0_0_1 = (Assignment)cGroup_6_0_0.eContents().get(1);
		private final RuleCall cStartSTRINGTerminalRuleCall_6_0_0_1_0 = (RuleCall)cStartAssignment_6_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_0_0_2 = (RuleCall)cGroup_6_0_0.eContents().get(2);
		private final Group cGroup_6_0_1 = (Group)cAlternatives_6_0.eContents().get(1);
		private final Keyword cAfterKeyword_6_0_1_0 = (Keyword)cGroup_6_0_1.eContents().get(0);
		private final Assignment cAfterAssignment_6_0_1_1 = (Assignment)cGroup_6_0_1.eContents().get(1);
		private final CrossReference cAfterActivityElementCrossReference_6_0_1_1_0 = (CrossReference)cAfterAssignment_6_0_1_1.eContents().get(0);
		private final RuleCall cAfterActivityElementQualifiedNameParserRuleCall_6_0_1_1_0_1 = (RuleCall)cAfterActivityElementCrossReference_6_0_1_1_0.eContents().get(1);
		private final Keyword cOffsetKeyword_6_0_1_2 = (Keyword)cGroup_6_0_1.eContents().get(2);
		private final Assignment cOffsetAssignment_6_0_1_3 = (Assignment)cGroup_6_0_1.eContents().get(3);
		private final RuleCall cOffsetINTTerminalRuleCall_6_0_1_3_0 = (RuleCall)cOffsetAssignment_6_0_1_3.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_0_1_4 = (RuleCall)cGroup_6_0_1.eContents().get(4);
		private final Group cGroup_6_1 = (Group)cUnorderedGroup_6.eContents().get(1);
		private final Alternatives cAlternatives_6_1_0 = (Alternatives)cGroup_6_1.eContents().get(0);
		private final Group cGroup_6_1_0_0 = (Group)cAlternatives_6_1_0.eContents().get(0);
		private final Keyword cEndsKeyword_6_1_0_0_0 = (Keyword)cGroup_6_1_0_0.eContents().get(0);
		private final Assignment cEndAssignment_6_1_0_0_1 = (Assignment)cGroup_6_1_0_0.eContents().get(1);
		private final RuleCall cEndSTRINGTerminalRuleCall_6_1_0_0_1_0 = (RuleCall)cEndAssignment_6_1_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_1_0_0_2 = (RuleCall)cGroup_6_1_0_0.eContents().get(2);
		private final Group cGroup_6_1_0_1 = (Group)cAlternatives_6_1_0.eContents().get(1);
		private final Keyword cDurationKeyword_6_1_0_1_0 = (Keyword)cGroup_6_1_0_1.eContents().get(0);
		private final Assignment cDurationAssignment_6_1_0_1_1 = (Assignment)cGroup_6_1_0_1.eContents().get(1);
		private final RuleCall cDurationINTTerminalRuleCall_6_1_0_1_1_0 = (RuleCall)cDurationAssignment_6_1_0_1_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_1_0_1_2 = (RuleCall)cGroup_6_1_0_1.eContents().get(2);
		private final Keyword cCompletenessKeyword_6_1_1 = (Keyword)cGroup_6_1.eContents().get(1);
		private final Assignment cCompletenessAssignment_6_1_2 = (Assignment)cGroup_6_1.eContents().get(2);
		private final RuleCall cCompletenessINTTerminalRuleCall_6_1_2_0 = (RuleCall)cCompletenessAssignment_6_1_2.eContents().get(0);
		private final Keyword cPercentSignKeyword_6_1_3 = (Keyword)cGroup_6_1.eContents().get(3);
		private final RuleCall cENDLINEParserRuleCall_6_1_4 = (RuleCall)cGroup_6_1.eContents().get(4);
		private final Group cGroup_6_2 = (Group)cUnorderedGroup_6.eContents().get(2);
		private final Keyword cDependsOnKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cDependenciesAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_6_2_1_0 = (CrossReference)cDependenciesAssignment_6_2_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_6_2_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_6_2_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_6_2_2 = (RuleCall)cGroup_6_2.eContents().get(2);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		
		//Activity:
		//	description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
		//	involvedResources+=ResourceInvolvement* CLOSEDCURLY)? (("starts" start=STRING ENDLINE | "after"
		//	after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & ("ends" end=STRING ENDLINE | "duration"
		//	duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE & ("dependsOn"
		//	dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
		@Override public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
		//involvedResources+=ResourceInvolvement* CLOSEDCURLY)? (("starts" start=STRING ENDLINE | "after"
		//after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & ("ends" end=STRING ENDLINE | "duration"
		//duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE & ("dependsOn"
		//dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Activity"
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//("involves" OPENCURLY involvedResources+=ResourceInvolvement* CLOSEDCURLY)?
		public Group getGroup_5() { return cGroup_5; }

		//"involves"
		public Keyword getInvolvesKeyword_5_0() { return cInvolvesKeyword_5_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_5_1() { return cOPENCURLYTerminalRuleCall_5_1; }

		//involvedResources+=ResourceInvolvement*
		public Assignment getInvolvedResourcesAssignment_5_2() { return cInvolvedResourcesAssignment_5_2; }

		//ResourceInvolvement
		public RuleCall getInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0() { return cInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_5_3() { return cCLOSEDCURLYTerminalRuleCall_5_3; }

		//("starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & ("ends"
		//end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE & ("dependsOn"
		//dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public UnorderedGroup getUnorderedGroup_6() { return cUnorderedGroup_6; }

		//"starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Alternatives getAlternatives_6_0() { return cAlternatives_6_0; }

		//"starts" start=STRING ENDLINE
		public Group getGroup_6_0_0() { return cGroup_6_0_0; }

		//"starts"
		public Keyword getStartsKeyword_6_0_0_0() { return cStartsKeyword_6_0_0_0; }

		//start=STRING
		public Assignment getStartAssignment_6_0_0_1() { return cStartAssignment_6_0_0_1; }

		//STRING
		public RuleCall getStartSTRINGTerminalRuleCall_6_0_0_1_0() { return cStartSTRINGTerminalRuleCall_6_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_0_0_2() { return cENDLINEParserRuleCall_6_0_0_2; }

		//"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Group getGroup_6_0_1() { return cGroup_6_0_1; }

		//"after"
		public Keyword getAfterKeyword_6_0_1_0() { return cAfterKeyword_6_0_1_0; }

		//after=[ActivityElement|QualifiedName]
		public Assignment getAfterAssignment_6_0_1_1() { return cAfterAssignment_6_0_1_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getAfterActivityElementCrossReference_6_0_1_1_0() { return cAfterActivityElementCrossReference_6_0_1_1_0; }

		//QualifiedName
		public RuleCall getAfterActivityElementQualifiedNameParserRuleCall_6_0_1_1_0_1() { return cAfterActivityElementQualifiedNameParserRuleCall_6_0_1_1_0_1; }

		//"offset"
		public Keyword getOffsetKeyword_6_0_1_2() { return cOffsetKeyword_6_0_1_2; }

		//offset=INT
		public Assignment getOffsetAssignment_6_0_1_3() { return cOffsetAssignment_6_0_1_3; }

		//INT
		public RuleCall getOffsetINTTerminalRuleCall_6_0_1_3_0() { return cOffsetINTTerminalRuleCall_6_0_1_3_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_0_1_4() { return cENDLINEParserRuleCall_6_0_1_4; }

		//("ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE
		public Group getGroup_6_1() { return cGroup_6_1; }

		//"ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE
		public Alternatives getAlternatives_6_1_0() { return cAlternatives_6_1_0; }

		//"ends" end=STRING ENDLINE
		public Group getGroup_6_1_0_0() { return cGroup_6_1_0_0; }

		//"ends"
		public Keyword getEndsKeyword_6_1_0_0_0() { return cEndsKeyword_6_1_0_0_0; }

		//end=STRING
		public Assignment getEndAssignment_6_1_0_0_1() { return cEndAssignment_6_1_0_0_1; }

		//STRING
		public RuleCall getEndSTRINGTerminalRuleCall_6_1_0_0_1_0() { return cEndSTRINGTerminalRuleCall_6_1_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_1_0_0_2() { return cENDLINEParserRuleCall_6_1_0_0_2; }

		//"duration" duration=INT ENDLINE
		public Group getGroup_6_1_0_1() { return cGroup_6_1_0_1; }

		//"duration"
		public Keyword getDurationKeyword_6_1_0_1_0() { return cDurationKeyword_6_1_0_1_0; }

		//duration=INT
		public Assignment getDurationAssignment_6_1_0_1_1() { return cDurationAssignment_6_1_0_1_1; }

		//INT
		public RuleCall getDurationINTTerminalRuleCall_6_1_0_1_1_0() { return cDurationINTTerminalRuleCall_6_1_0_1_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_1_0_1_2() { return cENDLINEParserRuleCall_6_1_0_1_2; }

		//"completeness"
		public Keyword getCompletenessKeyword_6_1_1() { return cCompletenessKeyword_6_1_1; }

		//completeness=INT
		public Assignment getCompletenessAssignment_6_1_2() { return cCompletenessAssignment_6_1_2; }

		//INT
		public RuleCall getCompletenessINTTerminalRuleCall_6_1_2_0() { return cCompletenessINTTerminalRuleCall_6_1_2_0; }

		//"%"
		public Keyword getPercentSignKeyword_6_1_3() { return cPercentSignKeyword_6_1_3; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_1_4() { return cENDLINEParserRuleCall_6_1_4; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_6_2() { return cGroup_6_2; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_6_2_0() { return cDependsOnKeyword_6_2_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_6_2_1() { return cDependenciesAssignment_6_2_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_6_2_1_0() { return cDependenciesActivityElementCrossReference_6_2_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_6_2_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_6_2_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_2_2() { return cENDLINEParserRuleCall_6_2_2; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_7() { return cCLOSEDCURLYTerminalRuleCall_7; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cSolidusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//Date:
		//	INT "/" INT "/" INT;
		@Override public ParserRule getRule() { return rule; }

		//INT "/" INT "/" INT
		public Group getGroup() { return cGroup; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//"/"
		public Keyword getSolidusKeyword_1() { return cSolidusKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }

		//"/"
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }

		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
	}
	
	
	public class ResponsibilityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Responsibility");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRESPONSIBLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRESPONSIBLERESPONSIBLEKeyword_0_0 = (Keyword)cRESPONSIBLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cACCOUNTABLEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cACCOUNTABLEACCOUNTABLEKeyword_1_0 = (Keyword)cACCOUNTABLEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCONSULTEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCONSULTEDCONSULTEDKeyword_2_0 = (Keyword)cCONSULTEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cINFORMEDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cINFORMEDINFORMEDKeyword_3_0 = (Keyword)cINFORMEDEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Responsibility:
		//	RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED;
		public EnumRule getRule() { return rule; }

		//RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED
		public Alternatives getAlternatives() { return cAlternatives; }

		//RESPONSIBLE
		public EnumLiteralDeclaration getRESPONSIBLEEnumLiteralDeclaration_0() { return cRESPONSIBLEEnumLiteralDeclaration_0; }

		//"RESPONSIBLE"
		public Keyword getRESPONSIBLERESPONSIBLEKeyword_0_0() { return cRESPONSIBLERESPONSIBLEKeyword_0_0; }

		//ACCOUNTABLE
		public EnumLiteralDeclaration getACCOUNTABLEEnumLiteralDeclaration_1() { return cACCOUNTABLEEnumLiteralDeclaration_1; }

		//"ACCOUNTABLE"
		public Keyword getACCOUNTABLEACCOUNTABLEKeyword_1_0() { return cACCOUNTABLEACCOUNTABLEKeyword_1_0; }

		//CONSULTED
		public EnumLiteralDeclaration getCONSULTEDEnumLiteralDeclaration_2() { return cCONSULTEDEnumLiteralDeclaration_2; }

		//"CONSULTED"
		public Keyword getCONSULTEDCONSULTEDKeyword_2_0() { return cCONSULTEDCONSULTEDKeyword_2_0; }

		//INFORMED
		public EnumLiteralDeclaration getINFORMEDEnumLiteralDeclaration_3() { return cINFORMEDEnumLiteralDeclaration_3; }

		//"INFORMED"
		public Keyword getINFORMEDINFORMEDKeyword_3_0() { return cINFORMEDINFORMEDKeyword_3_0; }
	}
	
	private final ProgramElements pProgram;
	private final ProjectElements pProject;
	private final AssumptionElements pAssumption;
	private final ConstraintElements pConstraint;
	private final ActivityGroupElements pActivityGroup;
	private final WBSImportElements pWBSImport;
	private final ResourcesImportElements pResourcesImport;
	private final PlanImportElements pPlanImport;
	private final QualifiedNameElements pQualifiedName;
	private final QualifiedNameWithWildCardElements pQualifiedNameWithWildCard;
	private final ActivityElementElements pActivityElement;
	private final ENDLINEElements pENDLINE;
	private final ResourcesElements pResources;
	private final ResourceElements pResource;
	private final CheckPointElements pCheckPoint;
	private final ResourceInvolvementElements pResourceInvolvement;
	private final ActivityElements pActivity;
	private final DateElements pDate;
	private final TerminalRule tOPENCURLY;
	private final TerminalRule tCLOSEDCURLY;
	private final ResponsibilityElements unknownRuleResponsibility;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PlanGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pProject = new ProjectElements();
		this.pAssumption = new AssumptionElements();
		this.pConstraint = new ConstraintElements();
		this.pActivityGroup = new ActivityGroupElements();
		this.pWBSImport = new WBSImportElements();
		this.pResourcesImport = new ResourcesImportElements();
		this.pPlanImport = new PlanImportElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pQualifiedNameWithWildCard = new QualifiedNameWithWildCardElements();
		this.pActivityElement = new ActivityElementElements();
		this.pENDLINE = new ENDLINEElements();
		this.pResources = new ResourcesElements();
		this.pResource = new ResourceElements();
		this.pCheckPoint = new CheckPointElements();
		this.pResourceInvolvement = new ResourceInvolvementElements();
		this.pActivity = new ActivityElements();
		this.pDate = new DateElements();
		this.tOPENCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "OPENCURLY");
		this.tCLOSEDCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CLOSEDCURLY");
		this.unknownRuleResponsibility = new ResponsibilityElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.lowcoupling.lng.plan.Plan".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
	//	("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//Project:
	//	description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? resources=Resources?
	//	(plans+=PlanImport ENDLINE)* ("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY
	//	constraints+=Constraint* CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY;
	public ProjectElements getProjectAccess() {
		return pProject;
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}

	//Assumption:
	//	"-" value=STRING ENDLINE;
	public AssumptionElements getAssumptionAccess() {
		return pAssumption;
	}
	
	public ParserRule getAssumptionRule() {
		return getAssumptionAccess().getRule();
	}

	//Constraint:
	//	"-" value=STRING ENDLINE;
	public ConstraintElements getConstraintAccess() {
		return pConstraint;
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//ActivityGroup:
	//	description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("dependsOn"
	//	dependencies+=[ActivityElement|QualifiedName]* ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
	//	CLOSEDCURLY;
	public ActivityGroupElements getActivityGroupAccess() {
		return pActivityGroup;
	}
	
	public ParserRule getActivityGroupRule() {
		return getActivityGroupAccess().getRule();
	}

	//WBSImport:
	//	"wbs" importURI= // feature must be named importURI
	//	STRING;
	public WBSImportElements getWBSImportAccess() {
		return pWBSImport;
	}
	
	public ParserRule getWBSImportRule() {
		return getWBSImportAccess().getRule();
	}

	//ResourcesImport:
	//	"resources" importURI= // feature must be named importURI
	//	STRING;
	public ResourcesImportElements getResourcesImportAccess() {
		return pResourcesImport;
	}
	
	public ParserRule getResourcesImportRule() {
		return getResourcesImportAccess().getRule();
	}

	//PlanImport:
	//	"plan" importURI= // feature must be named importURI
	//	STRING;
	public PlanImportElements getPlanImportAccess() {
		return pPlanImport;
	}
	
	public ParserRule getPlanImportRule() {
		return getPlanImportAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithWildCard:
	//	QualifiedName ".*"?;
	public QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return pQualifiedNameWithWildCard;
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}

	//ActivityElement:
	//	Activity | CheckPoint | ActivityGroup;
	public ActivityElementElements getActivityElementAccess() {
		return pActivityElement;
	}
	
	public ParserRule getActivityElementRule() {
		return getActivityElementAccess().getRule();
	}

	//ENDLINE:
	//	";";
	public ENDLINEElements getENDLINEAccess() {
		return pENDLINE;
	}
	
	public ParserRule getENDLINERule() {
		return getENDLINEAccess().getRule();
	}

	//Resources:
	//	"Resources" OPENCURLY resource+=Resource* CLOSEDCURLY;
	public ResourcesElements getResourcesAccess() {
		return pResources;
	}
	
	public ParserRule getResourcesRule() {
		return getResourcesAccess().getRule();
	}

	//Resource:
	//	"Resource" name=STRING ENDLINE;
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}

	//CheckPoint:
	//	description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (("date" end=STRING ENDLINE |
	//	"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%"
	//	ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
	public CheckPointElements getCheckPointAccess() {
		return pCheckPoint;
	}
	
	public ParserRule getCheckPointRule() {
		return getCheckPointAccess().getRule();
	}

	//ResourceInvolvement:
	//	resource=[Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE;
	public ResourceInvolvementElements getResourceInvolvementAccess() {
		return pResourceInvolvement;
	}
	
	public ParserRule getResourceInvolvementRule() {
		return getResourceInvolvementAccess().getRule();
	}

	//Activity:
	//	description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
	//	involvedResources+=ResourceInvolvement* CLOSEDCURLY)? (("starts" start=STRING ENDLINE | "after"
	//	after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & ("ends" end=STRING ENDLINE | "duration"
	//	duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE & ("dependsOn"
	//	dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
	public ActivityElements getActivityAccess() {
		return pActivity;
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Date:
	//	INT "/" INT "/" INT;
	public DateElements getDateAccess() {
		return pDate;
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//terminal OPENCURLY:
	//	"{";
	public TerminalRule getOPENCURLYRule() {
		return tOPENCURLY;
	} 

	//terminal CLOSEDCURLY:
	//	"}";
	public TerminalRule getCLOSEDCURLYRule() {
		return tCLOSEDCURLY;
	} 

	//enum Responsibility:
	//	RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED;
	public ResponsibilityElements getResponsibilityAccess() {
		return unknownRuleResponsibility;
	}
	
	public EnumRule getResponsibilityRule() {
		return getResponsibilityAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
