/*
 * generated by Xtext
 */
package com.lowcoupling.lng.plan.scoping;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.naming.DefaultDeclarativeQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import com.lowcoupling.lng.plan.plan.Project;

public class PlanScopeProvider extends AbstractDeclarativeScopeProvider {
	public IScope getScope (EObject context, EReference reference) {
		if(reference.getName().equals("wbsActivity")){
			EObject parent = context.eContainer();
			while ((parent!=null) && !(parent instanceof Project)){
				parent = parent.eContainer();
			}
			if(parent !=null && (parent instanceof Project)){
				Project project = (Project)parent;
				
				DefaultDeclarativeQualifiedNameProvider nameP = new DefaultDeclarativeQualifiedNameProvider();
			}

			
		}
		return super.getScope(context, reference);
	}
	//	public IScope getScope (EObject context, EReference reference) {
	////		if (reference.getName().equals("dependencies")){
	////			EObject parent = context.eContainer();
	////			while ((parent!=null) && !(parent instanceof Plans)){
	////				parent = parent.eContainer();
	////			}
	////			if(parent !=null && (parent instanceof Plans)){
	////				Plans plans = (Plans)parent;
	////				Iterator<Plan> planIt = plans.getPlan().iterator();
	////				List<EObject> activities = new ArrayList<EObject>();
	////				while(planIt.hasNext()){
	////					Plan plan = planIt.next();
	////					activities.addAll(plan.getActivities());
	////				}
	////				return  org.eclipse.xtext.scoping.Scopes.scopeFor(activities);
	////
	////			}
	////		}
	//
	//		return super.getScope(context, reference);
	//	}

}
